/* eslint-env mocha */
"use strict";

// tests for exampleFunction
// Generated by serverless-mocha-plugin

const mochaPlugin = require("serverless-mocha-plugin");
const dirtyChai = require("dirty-chai");
mochaPlugin.chai.use(dirtyChai);
const expect = mochaPlugin.chai.expect;

let wrapped = mochaPlugin.getWrapper("handler", "../../../handler", "handler");

describe("exampleFunction", () => {
    before((done) => {
        done();
    });

    it("implement tests here", () => {
        return wrapped
            .run({
                params: {
                    word: "value",
                },
            })
            .then((response) => {
                console.log(response);
                expect(response).to.not.be.empty();
            });
    });
});
